version: 2.1
images:
  maven:
    image: maven:latest
    auth:
      username: thangaram611
      password: Catalyst@1
jobs:
  maven-check:
    steps:
      - java -version
      - javac -version
      - mvn -version
  unit-test:
    steps:
      - mvn surefire-report:report
      - cd target
      - ls
    artifacts:
      upload:
        - type: zip
          regex:
            - '/catalyst/target/site/**'
          name: junit.zip
          location: stratus://pipe/
stages:
  - name: build
    image: maven
    jobs:
      - maven-check
      - unit-test