version: 2.1
images:
  maven:
    image: maven:latest
    auth:
      username: thangaram611
      password: Catalyst@1
jobs:
  maven:
    image: maven
    steps:
      - java -version
      - javac -version
      - mvn -version
stages:
  - name: build
    jobs:
      - maven