version: 2.1
images:
  maven:
    image: maven:latest
    auth:
      username: thangaram611
      password: Catalyst@1
  ubuntu:
    image: ubuntu:latest
    auth:
      username: thangaram611
      password: Catalyst@1
jobs:
  maven-check:
    steps:
      - java -version
      - javac -version
      - mvn -version
  unit-test:
    steps:
      - mvn surefire-report:report
    artifacts:
      upload:
        - type: zip
          regex:
            - /catalyst/target/site/**
          name: junit.zip
          location: stratus://pipe/
  package:
    steps:
      - mvn clean package -DskipTests=true
    artifacts:
      upload:
        - type: file
          name: SNAPSHOT.jar
          file: /catalyst/target/demo-0.0.1-SNAPSHOT.jar
          location: stratus://pipe/
  docker-build:
    image: ubuntu
    steps:
      - add-apt-repository ppa:cncf-buildpacks/pack-cli
      - apt-get update
      - apt-get install pack-cli
      - >-
        pack build sample-spring-boot --builder
        paketobuildpacks/builder-jammy-tiny --env BP_JVM_VERSION=21
stages:
  - name: build
    image: maven
    jobs:
      - maven-check
      - unit-test
      - - package
        - docker-build