version: 2.1
pipeline-when:
  - equals:
      - <<pipeline.event.branch>>
      - main
images:
  maven:
    image: maven:latest
    auth:
      username: thangaram611
      password: Catalyst@1
  pack:
    image: buildpacksio/pack:latest
    auth:
      username: thangaram611
      password: Catalyst@1
jobs:
  maven-check:
    steps:
      - java -version
      - javac -version
      - mvn -version
  unit-test:
    steps:
      - mvn surefire-report:report
    artifacts:
      upload:
        - type: zip
          regex:
            - '/catalyst/target/site/**'
          name: junit.zip
          location: stratus://pipe/
  package:
    steps:
      - ./mvnw clean package
    artifacts:
      upload:
        - type: file
          file: '/catalyst/target'
          name: demo-0.0.1-SNAPSHOT.jar
          location: stratus://pipe/
  docker-build:
    image: pack
    steps:
      - pack build sample-spring-boot --builder paketobuildpacks/builder-jammy-tiny --env BP_JVM_VERSION=21
stages:
  - name: build
    image: maven
    jobs:
      - maven-check
      - unit-test
      - - package
        - docker-build
