version: 2.1
pipeline-when:
  equal:
    - << pipeline.event.ref >>
    - main
images:
  maven:
    image: maven:latest
    auth:
      username: thangaram611
      password: Catalyst@1
  ubuntu:
    image: ubuntu:latest
    auth:
      username: thangaram611
      password: Catalyst@1
jobs:
  maven-check:
    steps:
      - echo "<< pipeline.event.ref >>"
      - java -version
      - javac -version
      - mvn -version
  unit-test:
    steps:
      - mvn surefire-report:report
    artifacts:
      upload:
        - type: zip
          regex:
            - /catalyst/target/site/**
          name: junit.zip
          location: stratus://pipe/
  package:
    steps:
      - mvn clean package -DskipTests=true
    artifacts:
      upload:
        - type: file
          name: SNAPSHOT.jar
          file: /catalyst/target/demo-0.0.1-SNAPSHOT.jar
          location: stratus://pipe/
  docker-build:
    image: ubuntu
    steps:
      - apt-get -y update
      - apt-get -y install curl
      - >-
        (curl -sSL
        "https://github.com/buildpacks/pack/releases/download/v0.33.2/pack-v0.33.2-linux.tgz"
        | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - >-
        pack build sample-spring-boot --builder
        paketobuildpacks/builder-jammy-tiny --env BP_JVM_VERSION=21
stages:
  - name: build
    image: maven
    jobs:
      - maven-check
      - unit-test
      - - package
        - docker-build